name: "Edit YAML file"
description: "Edit a YAML data file and optionally upload images"
title: "YAML Edit: "
labels: ["yml-edit"]
body:
  - type: dropdown
    id: yml_file
    attributes:
      label: "Which YAML file do you want to edit?"
      description: "Select a YAML file to edit"
      options:
        - "_data/learning_events.yml"
        - "_data/orgs.yml"
        - "_data/publications.yml"
        - "_data/social_media.yml"
    validations:
      required: true
  - type: textarea
    id: yaml_content
    attributes:
      label: "YAML Content"
      description: "Edit the YAML content below. You can drag and drop images into this textarea to upload them."
      placeholder: |
        events:
          - title: "Example Event"
            image: "../assets/img/example.jpg"
            description: "Event description"
      render: yaml
    validations:
      required: true
  - type: textarea
    id: comment
    attributes:
      label: "Additional comment"
      description: "Anything else you'd like to note"
      placeholder: "Optional comment..."
    validations:
      required: false